name: degreez
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.0 # Updated to latest version cuz of ai
  firebase_core: ^3.14.0 # Updated to latest version cuz of ai
  cloud_firestore: ^5.6.9 # Updated to latest version cuz of ai
  google_sign_in: ^6.3.0
  provider: ^6.1.1
  flutter_dotenv: ^5.2.1
  http: ^1.1.0
  shared_preferences: ^2.1.0
  calendar_view: ^1.4.0
  flutter_week_view: ^1.4.3
  intl: ^0.18.0    
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  file_picker: ^8.0.0+1

  firebase_ai: ^2.1.0
  flutter_map: ^8.1.1
  location: ^8.0.1
  geolocator: ^10.1.0
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/Faculties2024-2025/
    - assets/Faculties2023-2024/
