name: degreez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  firebase_core: ^2.1.1
  google_sign_in: ^6.3.0
  provider: ^6.1.1
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^4.17.5
  http: ^1.1.0
  shared_preferences: ^2.1.0
  calendar_view: ^1.4.0
  flutter_week_view: ^1.4.3
  intl: ^0.18.0
  url_launcher: ^6.1.10
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
