// lib/services/course_recommendation_service.dart

import 'dart:convert';
import 'dart:io';
import 'package:degreez/providers/course_provider.dart';
import 'package:flutter/material.dart';
import 'package:firebase_ai/firebase_ai.dart';
import '../models/course_recommendation_models.dart';
import '../services/ai/base_ai_service.dart';
import '../services/ai/ai_config.dart';
import '../services/ai/ai_utils.dart';
import 'optimization/ai_guided_hill_climbing_service.dart';
import 'optimization/candidate_validation_service.dart';

class CourseRecommendationService extends BaseAiService {
  final CourseProvider courseProvider;
  
  static const String _systemInstruction = '''
${AiConfig.baseSystemInstruction}

You are a course recommendation specialist for academic planning. Your role is to help students select appropriate courses for a specific semester based on their academic history, major requirements, and catalog information.

Always follow this process:
1. Analyze the student's context (major, completed courses, semester, preferences)
2. Review the catalog PDF to understand available courses (if provided)
3. Identify potential courses that align with the student's needs
4. Create final recommendations totaling 15-18 credit points
5. Provide clear reasoning for each recommendation

Consider these factors:
- Prerequisites and academic progression
- Major requirements vs electives
- Course difficulty and student's academic level
- Schedule conflicts and workload balance
- Student's stated preferences and career goals

Respond with valid JSON only, following the exact schema provided.
the course name must be in hebrew.
''';
  
  CourseRecommendationService(this.courseProvider)
    : super(
        modelName: AiConfig.defaultModel,
        systemInstruction: _systemInstruction,
        generationConfig: AiUtils.createJsonConfig(
          _createRecommendationSchema(),
        ),
      );

  /// Helper method to create a specialized model for different operations
  GenerativeModel _createSpecializedModel(
    Schema schema, {
    String? customSystemInstruction,
    bool useOptimizationModel = false,
  }) {
    final modelName = useOptimizationModel ? AiConfig.optimizationModel : AiConfig.defaultModel;
    return FirebaseAI.googleAI().generativeModel(
      model: modelName,
      systemInstruction: Content.text(customSystemInstruction ?? _systemInstruction),
      generationConfig: AiUtils.createJsonConfig(schema),
    );
  }

  /// Main method to generate course recommendations
  Future<CourseRecommendationResponse> generateRecommendations(
    CourseRecommendationRequest request, {
    bool fastMode = false, // NEW: Fast mode parameter
  }) async {
    // In fast mode, use default model; in optimization mode, use pro model
    final useOptimizationModel = !fastMode;
    try {
      // Parse actual year/semester based on display label like "Winter 2024-2025"
      final fallbackSemester = await courseProvider
          .getClosestAvailableSemester(request.semesterDisplayName);
      final parsed = courseProvider.parseSemesterCode(fallbackSemester);
      debugPrint(
        '🟢 Selected semester from UI: ${request.semesterDisplayName}',
      );
      debugPrint(
        '🔵 Using fallback semester for course data: $fallbackSemester',
      );
      debugPrint(
        'Parsed semester: $parsed for display name: $fallbackSemester',
      );
      if (parsed == null) {
        throw Exception(
          'Invalid semester display name: ${request.semesterDisplayName}',
        );
      }
      // Note: apiYear and semesterCode are available if needed for future use
      final (_, _) = parsed;
      
      // PHASE 0: Get valid candidates upfront for all phases
      debugPrint('🔍 Phase 0: Fetching valid candidates for all phases...');
      final validationService = CandidateValidationService(courseProvider);
      final validCandidates = await validationService.getValidCandidates(request);
      debugPrint('✅ Phase 0 complete: Found ${validCandidates.length} valid candidates');
      
      // PHASE 1: Get 3 candidate course sets from AI (with valid candidates)
      debugPrint('🚀 Phase 1: Generating 3 candidate course sets with valid candidates...');
      final multiSetResponse = await _identifyMultipleCandidateSets(request, validCandidates);
      debugPrint('✅ Phase 1 complete: Generated ${multiSetResponse.courseSets.length} course sets');

      if (multiSetResponse.courseSets.isEmpty) {
        throw Exception('No course sets generated by AI');
      }

      // PHASE 2: Optimization algorithm (hill climbing)
      if (fastMode) {
        debugPrint('⚡ Phase 2: FAST MODE - Skipping hill climbing optimization...');
        debugPrint('✅ Phase 2 complete: Using initial sets directly (fast mode)');
      } else {
        debugPrint('🔧 Phase 2: Running hill climbing optimization...');
      }
      
      final optimizedSets = await _optimizeCourseSetsWithHillClimbing(
        multiSetResponse.courseSets,
        request,
        validCandidates, // Pass the pre-fetched valid candidates
        fastMode, // Pass fast mode to optimization
        useOptimizationModel, // Pass optimization model preference
      );
      
      if (!fastMode) {
        debugPrint('✅ Phase 2 complete: Optimized ${optimizedSets.length} course sets');
      }

      // PHASE 3: AI chooses 3 final sets from optimized sets with one highlighted
      debugPrint('🧠 Phase 3: AI selecting 3 final sets with one highlighted...');
      final finalRecommendations = await _chooseFinalThreeSets(
        optimizedSets,
        request,
        validCandidates, // Pass valid candidates for storage
        useOptimizationModel, // Pass optimization model preference
      );
      debugPrint('✅ Phase 3 complete: Selected 3 final course sets with one highlighted');

      return finalRecommendations;
    } catch (e) {
      debugPrint('Course recommendation error: $e');
      throw Exception('Failed to generate course recommendations: $e');
    }
  }

  /// Step 1: Use structured JSON response to identify 3 candidate course sets
  Future<MultiSetCandidateResponse> _identifyMultipleCandidateSets(
    CourseRecommendationRequest request,
    List<dynamic> validCandidates, // NEW: Pass valid candidates
  ) async {
    // Use specialized model for multiple candidate course sets identification
    final candidateModel = _createSpecializedModel(_createMultiSetCandidateSchema());
    // printing the user context for debugging
    debugPrint('🔍 User context for candidate sets: ${request.userContext}');
    debugPrint('🔍 Preparing to identify multiple candidate sets...');
    // Prepare the prompt for 3 sets with valid candidates
    String prompt = '''
Please identify 3 different sets of candidate courses for the following student:

${request.userContext}

Target Semester: ${request.semesterDisplayName}

AVAILABLE VALID COURSES:
${jsonEncode(validCandidates)}

Requirements:
- Generate exactly 3 diverse course sets
- Each set should contain 5-7 courses totaling 15-18 credit points
- All course names must be in Hebrew
- Each set should represent a different strategic approach (e.g., core-focused, elective-heavy, prerequisite-clearing, etc.)
- Consider the student's academic level, major, and completed courses
- ONLY use courses from the provided valid courses list above
- Provide brief reasoning for each set's strategy

Return your response as valid JSON with the required schema.
Each course must have both courseId (course number) and courseName (Hebrew name).
''';

    // Generate response with or without catalog PDF
    final response = await _generateWithOptionalPdf(
      candidateModel,
      prompt,
      request.catalogFilePath,
    );

    try {
      final jsonData = jsonDecode(response.text ?? '{}');
      return MultiSetCandidateResponse.fromJson(jsonData);
    } catch (e) {
      throw Exception('Failed to parse multiple candidate sets response: $e');
    }
  }







  /// PHASE 2: AI-Guided Hill Climbing Optimization Algorithm
  Future<List<CourseSet>> _optimizeCourseSetsWithHillClimbing(
    List<CourseSet> initialSets,
    CourseRecommendationRequest request,
    List<dynamic> validCandidates, // NEW: Pre-fetched valid candidates
    bool fastMode, // NEW: Fast mode parameter
    bool useOptimizationModel, // NEW: Control optimization model usage
  ) async {
    if (fastMode) {
      debugPrint('⚡ Starting FAST MODE - skipping hill climbing optimization...');
    } else {
      debugPrint('🔧 Starting AI-guided hill climbing optimization...');
    }
    
    try {
      // Step 1: Use the pre-fetched valid candidates (no need to fetch again)
      debugPrint('✅ Step 1: Using pre-fetched valid candidates (${validCandidates.length} candidates)');
      
      // Step 2: Run AI-guided hill climbing optimization (or skip in fast mode)
      if (fastMode) {
        debugPrint('⚡ Step 2: FAST MODE - Skipping AI-guided hill climbing...');
      } else {
        debugPrint('🧠 Step 2: Running AI-guided hill climbing...');
      }
      
      final hillClimbingService = AiGuidedHillClimbingService();
      final optimizedSets = await hillClimbingService.optimize(
        initialSets: initialSets,
        validCandidates: validCandidates,
        request: request,
        maxIterations: 5, // Increased iterations for better optimization
        fastMode: fastMode, // NEW: Pass fast mode to optimization
      );
      
      // Note: Hill climbing service already uses AiConfig.optimizationModel for better performance
      
      if (fastMode) {
        debugPrint('✅ Fast mode optimization complete');
      } else {
        debugPrint('✅ AI-guided hill climbing optimization complete');
      }
      return optimizedSets;
      
    } catch (e) {
      debugPrint('❌ Error during hill climbing optimization: $e');
      debugPrint('🔄 Falling back to original sets');
      return initialSets; // Fallback to original sets if optimization fails
    }
  }

  /// PHASE 3: AI chooses 3 final sets from optimized sets with one highlighted
  Future<CourseRecommendationResponse> _chooseFinalThreeSets(
    List<CourseSet> optimizedSets,
    CourseRecommendationRequest request,
    List<dynamic> validCandidates, // NEW: Pass valid candidates for storage
    bool useOptimizationModel, // NEW: Control optimization model usage
  ) async {
    // Use specialized model for final set selection with optimization model
    final finalSelectionModel = _createSpecializedModel(
      _createFinalThreeSetSelectionSchema(),
      useOptimizationModel: useOptimizationModel, // Use parameter to control model choice
    );

    // Prepare the prompt for final selection
    String prompt = '''
You have been given optimized course sets from a hill climbing algorithm. 
Please analyze all sets and present the best 3 sets for the following student, with one highlighted as the primary recommendation:

STUDENT CONTEXT:
${request.userContext}

TARGET SEMESTER: ${request.semesterDisplayName}

OPTIMIZED COURSE SETS:
${jsonEncode(optimizedSets.map((set) => set.toJson()).toList())}

REQUIREMENTS:
- Choose exactly 3 sets that best serve the student
- Each set should offer a different strategic approach
- Mark one set as the "primary" recommendation (highlighted)
- Provide brief reasoning for each set
- Consider the student's preferences, academic level, and degree progression

Return your response as valid JSON with the required schema.
''';

    final response = await _generateWithOptionalPdf(
      finalSelectionModel,
      prompt,
      request.catalogFilePath,
    );

    try {
      final jsonData = jsonDecode(response.text ?? '{}');
      
      // Convert the response to our existing CourseRecommendationResponse format
      final selectedSets = jsonData['selectedSets'] as List;
      final primarySetId = jsonData['primarySetId'] as int;
      final allRecommendations = <CourseRecommendation>[];
      
      // Convert all 3 sets to recommendations
      for (int setIndex = 0; setIndex < selectedSets.length; setIndex++) {
        final set = selectedSets[setIndex];
        final courses = set['courses'] as List;
        final isPrimary = set['setId'] == primarySetId;
        
        for (final course in courses) {
          allRecommendations.add(CourseRecommendation(
            courseId: course['courseId'],
            courseName: course['courseName'],
            creditPoints: (course['creditPoints'] as num?)?.toDouble() ?? 3.0,
            reason: set['reasoning'] ?? 'AI recommended',
            priority: isPrimary ? 1 : (setIndex + 2), // Primary gets priority 1, others get 2,3
            category: isPrimary ? 'Primary Set' : 'Set ${setIndex + 1}',
          ));
        }
      }
      
      return CourseRecommendationResponse(
        recommendations: allRecommendations,
        totalCreditPoints: allRecommendations.fold(0.0, (sum, rec) => sum + rec.creditPoints),
        summary: jsonData['summary'] ?? 'AI selected 3 optimal course sets with one highlighted',
        reasoning: jsonData['overallReasoning'] ?? 'Selected based on student preferences with primary recommendation highlighted',
        generatedAt: DateTime.now(),
        originalRequest: request,
        validCandidates: validCandidates, // NEW: Include valid candidates for feedback optimization
      );
    } catch (e) {
      throw Exception('Failed to parse final three sets selection response: $e');
    }
  }

  /// Helper method to generate content with optional PDF
  Future<GenerateContentResponse> _generateWithOptionalPdf(
    GenerativeModel model,
    String prompt,
    String? catalogFilePath,
  ) async {
    if (catalogFilePath != null && catalogFilePath.isNotEmpty) {
      final catalogFile = File(catalogFilePath);

      // Validate file before processing
      if (!await AiUtils.validateFileSize(catalogFile)) {
        throw Exception(AiUtils.getFileSizeErrorMessage());
      }

      if (!await AiUtils.validatePdfFormat(catalogFile)) {
        throw Exception('Invalid PDF file format');
      }

      final catalogBytes = await catalogFile.readAsBytes();
      return await model.generateContent([
        AiUtils.createPdfContent(prompt, catalogBytes),
      ]);
    } else {
      return await model.generateContent([Content.text(prompt)]);
    }
  }

  /// NEW: Schema for 3 candidate course sets
  static Schema _createMultiSetCandidateSchema() {
    return Schema.object(
      properties: {
        'courseSets': Schema.array(
          items: Schema.object(
            properties: {
              'courses': Schema.array(
                items: Schema.object(
                  properties: {
                    'id': Schema.string(description: 'Course ID/Number'),
                    'name': Schema.string(description: 'Course name in Hebrew'),
                  },
                ),
                description: '5-7 courses totaling 15-18 credit points',
              ),
              'totalCredits': Schema.number(
                description: 'Total credit points for this set (15-18)',
              ),
              'reasoning': Schema.string(
                description: 'Strategy reasoning for this specific set in a few words',
              ),
            },
          ),
          description: 'Array of exactly 3 diverse course sets',
        ),
        'overallReasoning': Schema.string(
          description: 'Overall explanation of the 3 different strategies used in a few words',
        ),
      },
    );
  }

  /// Schema for final recommendations
  static Schema _createRecommendationSchema() {
    return Schema.object(
      properties: {
        'recommendations': Schema.array(
          items: Schema.object(
            properties: {
              'courseId': Schema.string(),
              'courseName': Schema.string(),
              'creditPoints': Schema.number(),
              'reason': Schema.string(
                description: 'Why this course is recommended',
              ),
              'priority': Schema.integer(
                description: 'Priority 1-5 (1=highest)',
              ),
              'category': Schema.string(
                description: 'e.g., Core, Elective, Prerequisites',
              ),
            },
          ),
          description:
              'List of recommended courses (target 15-18 total credit points)',
        ),
        'totalCreditPoints': Schema.number(),
        'summary': Schema.string(
          description: 'Brief summary of the recommendation set',
        ),
        'reasoning': Schema.string(
          description: 'Overall reasoning for the recommendation strategy',
        ),
      },
    );
  }

  /// Schema for final three sets selection (AI chooses 3 with one highlighted)
  static Schema _createFinalThreeSetSelectionSchema() {
    return Schema.object(
      properties: {
        'selectedSets': Schema.array(
          items: Schema.object(
            properties: {
              'setId': Schema.number(description: 'Original set ID'),
              'strategy': Schema.string(description: 'Strategy name for this set'),
              'reasoning': Schema.string(description: 'Why this set was chosen'),
              'courses': Schema.array(
                items: Schema.object(
                  properties: {
                    'courseId': Schema.string(description: 'Course ID/number'),
                    'courseName': Schema.string(description: 'Course name in Hebrew'),
                    'creditPoints': Schema.number(description: 'Credit points for this course'),
                  },
                ),
                description: 'Courses in this selected set',
              ),
              'totalCredits': Schema.number(description: 'Total credits for this set'),
            },
          ),
          description: 'Exactly 3 selected course sets',
        ),
        'primarySetId': Schema.number(description: 'ID of the primary/highlighted set'),
        'summary': Schema.string(description: 'Brief summary of the selection'),
        'overallReasoning': Schema.string(description: 'Overall reasoning for choosing these 3 sets'),
        'comparison': Schema.string(description: 'How the 3 sets differ and complement each other'),
      },
    );
  }

  /// Interactive feedback processing method
  Future<FeedbackResponse> processFeedback(
    FeedbackProcessingRequest request,
  ) async {
    final session = request.session;
    final feedback = request.feedback;

    // Use pre-fetched valid candidates from the session (optimization)
    List<dynamic> validCandidates;
    if (session.validCandidates == null || session.validCandidates!.isEmpty) {
      debugPrint('⚠️ Feedback: No valid candidates found in session, fetching fresh candidates...');
      final validationService = CandidateValidationService(courseProvider);
      validCandidates = await validationService.getValidCandidates(session.originalRequest);
      debugPrint('✅ Feedback: Found ${validCandidates.length} valid candidates for replacements');
    } else {
      validCandidates = session.validCandidates!;
      debugPrint('✅ Feedback: Using pre-fetched valid candidates from session (${validCandidates.length} candidates for replacements)');
    }

    // Use specialized model for feedback processing with function calling
    final feedbackModel = _createSpecializedModel(
      _createFeedbackResponseSchema(),
      customSystemInstruction: _getFeedbackSystemInstruction(),
    );

    // Prepare conversation context for the AI
    final conversationContext = _buildConversationContext(session);
    final currentRecommendationsJson = session.currentRecommendations
        ?.map((set) => set.toJson())
        .toList();

    final prompt = '''
You are an intelligent course recommendation assistant. A student has provided feedback on their course recommendations. Your task is to analyze this feedback and intelligently modify the course sets to better meet their needs.

IMPORTANT: You must maintain the multi-stage optimization approach:
1. Keep the academic logic and constraints in mind
2. Ensure course availability and prerequisites are respected  
3. Maintain 15-18 credit balance per set
4. Consider the student's academic progression

ORIGINAL CONTEXT:
${session.originalRequest.userContext}

SEMESTER: ${session.originalRequest.semesterDisplayName}

AVAILABLE VALID COURSES FOR REPLACEMENTS:
${jsonEncode(validCandidates)}

CONVERSATION HISTORY:
$conversationContext

CURRENT COURSE SETS:
${jsonEncode(currentRecommendationsJson)}

USER FEEDBACK:
Type: ${feedback.type.name}
Message: "${feedback.message}"
${feedback.courseId != null ? 'Specific Course: ${feedback.courseId}' : ''}
${feedback.setId != null ? 'Specific Set: ${feedback.setId}' : ''}

ANALYSIS TASK:
Based on this feedback, intelligently respond to the user. Consider:

1. **If REPLACE feedback**: Find suitable replacement courses from the AVAILABLE VALID COURSES list above that maintain academic logic and explain the alternatives
2. **If QUESTION feedback**: Provide detailed, helpful answers about the recommendations, courses, or academic planning

REQUIREMENTS:
- For REPLACE: Return exactly 3 updated course sets with the requested replacement
- For QUESTION: Keep current sets unchanged but provide detailed explanation
- Each set should have 5-7 courses totaling 15-18 credits
- All course names must be in Hebrew
- **IMPORTANT**: Include actual credit points for each course (not average or default values)
- **CRITICAL**: When replacing courses, ONLY use courses from the AVAILABLE VALID COURSES list above
- When replacing courses, ensure the new course's actual credit points are used
- Provide clear reasoning for changes made
- Maintain academic progression logic
- Consider course availability in the specified semester
- Consider course availability in the specified semester

Respond with valid JSON following the schema. Focus on creating sets that address the user's feedback while maintaining educational value.
''';

    final response = await feedbackModel.generateContent([
      Content.text(prompt),
    ]);

    return _parseFeedbackResponse(response.text ?? '{}');
  }

  /// Build conversation context string for AI
  String _buildConversationContext(RecommendationSession session) {
    final buffer = StringBuffer();
    
    for (final message in session.conversation) {
      final role = message.isUser ? 'USER' : 'ASSISTANT';
      buffer.writeln('$role: ${message.content}');
      
      if (message.feedback != null) {
        final feedback = message.feedback!;
        buffer.writeln('  - Feedback Type: ${feedback.type.name}');
        buffer.writeln('  - Message: ${feedback.message}');
        if (feedback.courseId != null) {
          buffer.writeln('  - Course ID: ${feedback.courseId}');
        }
        if (feedback.setId != null) {
          buffer.writeln('  - Set ID: ${feedback.setId}');
        }
      }
      
      if (message.recommendations != null) {
        buffer.writeln('  - Provided ${message.recommendations!.length} course sets');
      }
      
      buffer.writeln();
    }
    
    return buffer.toString();
  }

  /// Get system instruction for feedback processing
  String _getFeedbackSystemInstruction() {
    return '''
You are an intelligent course recommendation assistant that can process user feedback and adjust recommendations accordingly.

Your capabilities:
1. Analyze user feedback (likes, dislikes, specific requests)
2. Modify course recommendations based on feedback
3. Explain your reasoning clearly

Guidelines:
- Always maintain academic logic (prerequisites, progression, credit balance)
- Consider user preferences while ensuring degree requirements are met
- Be transparent about what changes you made and why
- Always return exactly 3 updated course sets
- Prioritize user satisfaction while maintaining academic validity

Your responses must be in valid JSON format with the specified schema.
''';
  }

  /// Create JSON schema for feedback responses
  Schema _createFeedbackResponseSchema() {
    return Schema.object(
      properties: {
        'updatedRecommendations': Schema.array(
          items: Schema.object(
            properties: {
              'setId': Schema.integer(),
              'courses': Schema.array(
                items: Schema.object(
                  properties: {
                    'id': Schema.string(),
                    'name': Schema.string(),
                    'creditPoints': Schema.number(description: 'Credit points for this course'),
                  },
                ),
              ),
              'totalCredits': Schema.number(),
              'reasoning': Schema.string(),
            },
          ),
        ),
        'explanation': Schema.string(),
        'usedAlgorithm': Schema.boolean(),
        'fetchedNewData': Schema.boolean(),
      },
    );
  }



  /// Parse feedback response from AI
  FeedbackResponse _parseFeedbackResponse(String responseText) {
    try {
      final jsonData = jsonDecode(responseText);
      
      return FeedbackResponse.fromJson(jsonData);
    } catch (e) {
      debugPrint('Failed to parse feedback response: $e');
      
      // Return default response if parsing fails
      return const FeedbackResponse(
        updatedRecommendations: [],
        explanation: 'Sorry, I encountered an error processing your feedback. Please try again.',
        usedAlgorithm: false,
        fetchedNewData: false,
      );
    }
  }

}
