// File generated by FlutterFire CLI.
// This file is a placeholder for your actual firebase_options.dart file
// You should replace this with the file generated by the FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhjdzM_Eb6satYCro6ZwPKWBHi-CFHM6A',
    appId: '1:557089994187:android:ca0bf2a0953eaaff43f24e',
    messagingSenderId: '557089994187',
    projectId: 'degreez-fbec6',
    storageBucket: 'degreez-fbec6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhjdzM_Eb6satYCro6ZwPKWBHi-CFHM6A',
    appId: '1:557089994187:web:d2bea349b681ac8743f24e',
    messagingSenderId: '557089994187',
    projectId: 'degreez-fbec6',
    storageBucket: 'degreez-fbec6.firebasestorage.app',
    authDomain: 'degreez-fbec6.firebaseapp.com',
  );
}