// File generated by FlutterFire CLI.
// This file is a placeholder for your actual firebase_options.dart file
// You should replace this with the file generated by the FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default Firebase configuration options for the current platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Read web config from environment variables (from .env) so you can
      // provide web credentials without running the FlutterFire CLI.
      final apiKey = dotenv.env['WEB_API_KEY'];
      final appId = dotenv.env['WEB_APP_ID'];
      final messagingSenderId = dotenv.env['WEB_MESSAGING_SENDER_ID'];
      final projectId = dotenv.env['WEB_PROJECT_ID'];
      final authDomain = dotenv.env['WEB_AUTH_DOMAIN'];
      final storageBucket = dotenv.env['WEB_STORAGE_BUCKET'];
      final measurementId = dotenv.env['WEB_MEASUREMENT_ID'];

      if (apiKey != null && appId != null && projectId != null) {
        return FirebaseOptions(
          apiKey: apiKey,
          appId: appId,
          messagingSenderId: messagingSenderId ?? '',
          projectId: projectId,
          authDomain: authDomain,
          storageBucket: storageBucket,
          measurementId: measurementId,
        );
      }

      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for Web - set WEB_API_KEY, WEB_APP_ID and WEB_PROJECT_ID in your .env or run the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: dotenv.env['WEB_APP_ID']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
  );
}